### PR TITLE
added privacy policy page

### PR DESCRIPTION
**Pull request by donkim1127**
Created a new component for the privacy policy page.
Made a paragraph element containing what information we collect from users and that
we will not disclose any of it or sell it for dark practices

### CODE REVIEW

**Comment by kevinliang43** [comment]
@donkim1127 Let's include a screenshot of what the first iteration of the policy page would look like, to this PR for documentation purposes (We can add this to the PR description).

Can you add 1 screenshot of the page in wide screen, and 1 with small screen?

**Comment by donkim1127** [comment]
bazaar privacy policy wide screen
bazaar privacy policy small screen

**Comment by kevinliang43** [comment]
One last thing before merging:

Jose uploaded a [Privacy Policy Doc](https://github.com/kevinliang43/wbdv-sp20-bazaar-react-client/files/4396654/Writing.a.Privacy.Policy.docx) that contains requirements for what composes a privacy policy. Can you go through this and see if we hit all the checkboxes in this current iteration?

**Comment by kevinliang43** [comment]
Good for first iteration. Lets revisit this later, since this is a 'nice-to-have'

**Pull request merged**
